### ISSUE TITLE
Please create gimp 2.10.x kits 

### ISSUE THREAD

**Issue by luzpaz** [funtoo/media-kit#2]
https://github.com/funtoo/media-kit/tree/1.0-prime/media-gfx/gimp does not have any 2.10.x representation. As per https://repology.org/metapackage/gimp/badges
which doesn't show that Funtoo is up to date. There is a badge that can track this, see below:

[![Packaging status](https://repology.org/badge/vertical-allrepos/gimp.svg)](https://repology.org/metapackage/gimp/versions)

**Comment by luzpaz** [comment]
bump

**Comment by mrl5** [comment]
hello @luzpaz - if you'd like to report a bug kindly use https://bugs.funtoo.org/

you can also reach us on Discord - for more info check https://www.funtoo.org/Welcome
